### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by david-allison** [david-allison/manx-corpus-search#49]
Now we have a domain, we should focus more on SEO. Lots of low hanging fruit here:

- [x] Add details to the HEAD of the main corpus search page
- [x] Provide HTML versions of works
- [ ] Backlinks (for later, long-term domains requested from govt)

**Comment by david-allison-1** [comment]
Enabled GZIP

```
gzip on;
gzip_disable "msie6";

gzip_comp_level 6;
gzip_min_length 1100;
gzip_buffers 16 8k;
gzip_proxied any;
gzip_types
    text/plain
    text/css
    text/js
    text/xml
    text/javascript
    application/javascript
    application/json
    application/xml
    application/rss+xml
    image/svg+xml;
```

Still at 98/100 on [Google's page speed](https://developers.google.com/speed/pagespeed/insights/?url=manxcorpus.com&tab=mobile&hl=en_GB)

**Comment by david-allison-1** [comment]
Number 1 on Google for "Manx Corpus Search".

Page 10 for "Manx Corpus"
