### ISSUE TITLE
Make the search language English/Manx selectable in the URL

### ISSUE THREAD

**Issue by caoimhinsmo** [david-allison/manx-corpus-search#98]
I have added ManxCorpus to the Manx-English dictionaries accessible via Multidict

    https://multidict.net/multidict/?sl=gv&tl=en&dict=MxCorp&word=snaue 

Very easy, since the URL

    https://manxcorpus.com/?q=snaue

will search for the Manx word “snaue”.

However, I have bother doing things English searches, since I can’t find any URL which will search ManxCorpus for the English word “crawl”, for example.  What I would hope for is something like

    https://manxcorpus.com/?q=crawl&lang=en

**Comment by david-allison** [comment]
Dr. Ó Donnaíle,

Thank you **so much** for taking the time to raise the issue.

This feature is now live: https://manxcorpus.com/?q=crawl&lang=en . Please let me know if you need anything further.

Best wishes,
David
